# Site Settings
title: Tiny Books by Christopher Murphy
email: info@tinybooks.org
description: > # This means to ignore newlines until "baseurl:"
  Tiny Books Â· Short Books for Creative Entrepreneurs
baseurl: "" # The subpath of your site, e.g. /blog/.
# url: "http://tinybooks.org" # The base hostname and protocol for your site.
# url: "http://127.0.0.1:4000/" # The base hostname and protocol for your site.
url: "http://tinybooks.org/" # The base hostname and protocol for your site.
twitter_username: fehler
github_username: tinybooks
paginate: 10
exclude: node_modules
permalink: /journal/:title
paginate_path: "/journal/page:num/"

# Build Settings
markdown: kramdown
sass:
  style: compressed